//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyroidDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease_information
    {
        public string disease { get; set; }
        public string thumbnail { get; set; }
        public string description { get; set; }
        public string disease_content { get; set; }
        public string symptom { get; set; }
        public string cause { get; set; }
        public string treatment { get; set; }
        public string timestamp { get; set; }
    }
}
