//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyroidDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class disease_forum
    {
        public int idForum { get; set; }
        public string disease_name { get; set; }
        public string post_title { get; set; }
        public string post_description { get; set; }
        public string timestamp { get; set; }
        public string user_name { get; set; }
        public string post_img { get; set; }
    }
}
