//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyroidDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class drug_dosage
    {
        public int idDosage { get; set; }
        public string drug_name { get; set; }
        public string drug_dose { get; set; }
        public int report_id { get; set; }
        public string drug_days { get; set; }
        public int patient_id { get; set; }
        public string drug_img { get; set; }
    }
}
