//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyroidDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_information
    {
        public int patient_id { get; set; }
        public string user_id { get; set; }
        public string diagnosis { get; set; }
        public string ic_number { get; set; }
        public string date_of_birth { get; set; }
        public string gender { get; set; }
        public string blood_type { get; set; }
        public string timestamp { get; set; }
        public string doctor_id { get; set; }
    }
}
