//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThyroidDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient_report()
        {
            this.drug_dosage = new HashSet<drug_dosage>();
        }
    
        public int report_id { get; set; }
        public int patient_id { get; set; }
        public double FT4 { get; set; }
        public double TSH { get; set; }
        public string timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<drug_dosage> drug_dosage { get; set; }
    }
}
